numbers = [3, 5, 7, 5, 8, 1]
numbers.append(20)
numbers.insert(0, 10)
numbers.remove(8)
numbers.pop()
numbers.sort()
numbers.reverse()
print(numbers)
print(50 in numbers)
print(numbers.index(7))
print(numbers.count(5))